[app_config]
# --- アプリケーション設定ID ---
# あなたのGoogleスプレッドシートIDとドライブフォルダIDを記入してください
SPREADSHEET_ID = 1sEzw59aswIlA-8_CTyUrRBLN7OnrRIJERKUZ_bELMrY" 
WORKSHEET_NAME = "実験用" 
DRIVE_FOLDER_ID = "1malvBDg-fIvzFWqxAyvOwL18hoKzzJoN?ths=true"
DRAFT_SUBJECT_TEMPLATE = "【日報】{date}の日記更新"
DRAFT_DEFAULT_TO_ADDRESS = "example@mailinglist.com"


[service_account]
# ⚠️ ここは空のままにしておきます！ ⚠️
# 秘密の鍵はStreamlit Cloudの画面で直接入力するため、ここでは空欄のままです。

type = "service_account"
project_id = ""
private_key_id = ""
private_key = ""
client_email = ""
client_id = ""
auth_uri = ""
token_uri = ""
auth_provider_x509_cert_url = ""
client_x509_cert_url = ""
universe_domain = ""
