[google_resources]
spreadsheet_id = "1sEzw59aswIlA-8_CTyUrRBLN7OnrRIJERKUZ_bELMrY"

[sheet_names]
registration_sheet = "日記登録用シート"
usable_diary_sheet = "写メ日記集めシート"
account_sheet = "写メ日記アカウント"

[gcp_service_account]
type = "service_account"
project_id = "intense-clarity-478212-k2"
private_key_id = "bf4c7dab6dc57522387cab2189965192276953e7"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDXM5SqpdOToLlc
4Skck/yCWzuGP5Zqz9916O0igyBvTQgL2NgfA12GTYE5elFlhs3KZYOGF+MOs20M
5+K5JY2fsy4esm7exVW5ndgbcsFYkc8RGbcjdkge07zHRA0tARTsWfIliJdfm1V2
bu/5VICFPTh8Ks/v703/4mBKlDWCyyni1JiYAt61LztvaHuTxbFc5SNQWVeuULZj
jIrC/G4/6m4fMjVhbiLe+tAtyVV437Mo2+edanny47jH+zW4MUxwWwkSPEU1bUR1
iEZ5vyXrms8TubfsRfYNOpJHF6f86Y46Xno77uDTqA8Q+x6Z1sDrkqieIhugwtk7
074qNn53AgMBAAECggEAAl/ETRmlOuS0Bs1JGdKcH4gIIRQEgcsnSPK34wCVVAUC
iLbss3LjDj8+pLavvTH+hTQXflw3GgtqsZDBVI+Qf2mHobkQNg7xQin2n17luSdq
pGKnPZHpe8WUOJKMnql7ZJwdasKWAO0CxVq19Qc0n8OsItqKDriSILeLnmcCLB4y
ney8bIWF7doh2NNNMviaEZAakV0uAOwH/tePv4y9wVE++x4YpC3a9TwrJ3B2sDOO
wmMHxafSpLP29Eyg2wZOlNjw5DK5eSBvfdWZoHANb/v660YnmYY9oG+yakGTtrdV
c0uYWW18zy5X9h40A0abVJ39FAkUAAitq7UMj1AtsOQKBgQDuGWQs96cPVCv9VpX
i/P6auoXQOY74K0TEu99I3/9MTEvYnBT4ccFzGetu/4dyvEKYduz+semJlSdH5oe
BlcgDbS02Buzy2huBDBjG7bqFijsOcfcHu5xU/lC2gnRMFZBG75I5fDnRRYup9cL
6tK/iQzcPkYpdNPdenFJ+DIWc6wKBgQDnYXxZCrhHwsP0WLthMWswpNbfrmSQ5yu
OjT7c7jQv2WQg7KbGGS2m/r2fLbcHAhr8FfJj0lZnGzMI0WqHPYiE5O2ikbZfSeo
rxNYASJOr8IT/NYL7cj4bGUiUPp8VhquL5CVj/okQe2urBckuo8U2Wk9hRIjGJPk
qXDS8r9ZRpQKBgQDZdqVxEKwrqvQWiYuSawHbrjpjiP6UmWhQy0rPU47oT9MCPuR
EWhmWl/jZQ1ehqmKkwBILOdGUEH91Aw+GgpfQ0Vl2u/KUiDKQtcy3fA9cwnjX46z
9ChRp6HEtkI7JovRIZa1HBbgMQqGiFM4FjxwJatySQpp+MM8yQVJyv9sVCwKBgQC
ydxHHSCptRz+HV21oAQsRYQNPUh7FWVjSQgWruJtOENpXPtE/2KnKtY+imEskv63
6pB7qeZElQ+hwM758A60p+72C9+r3wnY5PkBlxZUJOKIMisS1lx9qHW1K0qY3n0D
vzJA+eVRU/y1Do1nSfIUfcDbr6kWouJrI/oe6xdGD9QKBgQDX3JjCz+en+vJf6JY
ySHwnP4YzAb2jiuDdhsG7YhLBrAM2mjAoPXeQU9Mu/eqjK6JaiBKUAofSWaSVWZJ
iju9pNeQ9cTEBRgIv2t3GyDQCjDMzE7+GIc16TH4wl4ceT6W3enZawUfXi4XnlfT
Lo2UJ+Af6Duxn97bQ3nH6vrtjHw==
-----END PRIVATE KEY-----
"""
client_email = "streamlit-diary-robot@intense-clarity-478212-k2.iam.gserviceaccount.com"
client_id = "110010709702579450772"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-diary-robot@intense-clarity-478212-k2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
