[app_config]

--- Google Sheets の設定 ---

いただいたスプレッドシートID

SPREADSHEET_ID = "1sEzw59aswIlA-8_CTyUrRBLN7OnrRIJERKUZ_bELMrY"

ワークシート名 (アプリケーション内のキーとマッピング)

WORKSHEET_REGISTER_NAME = "日記登録用"
WORKSHEET_CONTACT_NAME = "連絡先登録用"
WORKSHEET_USABLE_NAME = "【使用可能日記文】"

「実験用」を履歴（FULL_HISTORY）として使用します

WORKSHEET_FULL_HISTORY_NAME = "実験用"

--- Google Drive の設定 ---

いただいた「写メ日記画像用」フォルダのID

DRIVE_ROOT_FOLDER_ID = "1malvBDg-fIvzFWqxAyOwsL18hoKzzJo"

