# サービスアカウント認証情報 (JSONキーをTOML形式に変換)
# StreamlitのSecrets画面で設定する場合、[gcp_service_account]の下のキーと値を設定します。
[gcp_service_account]
type = "service_account"
project_id = "intense-clarity-478212-k2"
private_key_id = "bf4c7dab6dc57522387cab2189965192276953e7"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDXM5SqpdOToLlc\n4Skck/yCWzuGP5Zqz9916O0igyBvTQgL2NgfA12GTYE5elFlhs3KZYOGF+MOs20M\n5+K5JY2fsy4esm7exVW5ndgbcsFYkc8RGbcjdkge07zHRA0tARTsWfIliJdfm1V2\nbu/5VICFPTh8Ks/v703/4mBKlDWCyyni1JiYAt61LztvaHuTxbFc5SNQWVeuULZj\njIrC/G4/6m4fMjVhbiLe+tAtyVV437Mo2+edanny47jH+zW4MUxwWwkSPEU1bUR1\niEZ5vyXrms8TubfsRfYNOpJHF6f86Y46Xno77uDTqA8Q+x6Z1sDrkqieIhugwtk7\n074qNn53AgMBAAECggEAAl/ETRmlOuS0Bs1JGdKcH4gIIRQEgcsnSPK34wCVVAUC\niLbss3LjDj8+pLavvTH+hTQXflw3GgtqsZDBVI+Qf2mHobkQNg7xQin2n17luSdq\npGKnPZHpe8WUOJKMnql7ZJwdasKWAO0CxVq19Qc0n8OsItqKDriSILeLnmcCLB4y\ney8bIWF7doh2NNNMviaEZAakV0uAOwH/tePv4y9wVE++x4YpC3a9TwrJ3B2sDOOw\nmMHxafSpLP29Eyg2wZOlNjw5DK5eSBvfdWZoHANb/v660YnmYY9oG+yakGTtrdVc\n0uYWW18zy5X9h40A0abVJ39FAkUAAitq7UMj1AtsOQKBgQDuGWQs96cPVCv9VpXi\n/P6auoXQOY74K0TEu99I3/9MTEvYnBT4ccFzGetu/4dyvEKYduz+semJlSdH5oeB\nlcgDbS02Buzy2huBDBjG7bqFijsOcfcHu5xU/lC2gnRMFZBG75I5fDnZRYup9cL6\ntK/iQzcPkYpdNPdenFJ+DIWc6wKBgQDnYXxZCrhHwsP0WLthMWswpNbfrmSQ5yuO\njT7c7jQv2WQg7KbGGS2m/r2fLbcHAhr8FfJj0lZnGzMI0WqHPYiE5O2ikbZfSeor\nxNYASJOr8IT/NYL7cj4bGUiUPp8VhquL5CVj/okQe2urBckuo8U2Wk9hRIjGJpkq\nXDS8r9ZRpQKBgQDZdqVxEKwrqvQWiYuSawHbrjpjiP6UmWhQy0rPU47oT9MCPuRE\nWhmWl/jZQ1ehqmKkwBILOdGUEH91Aw+GgpfQ0Vl2u/KUiDKQtcy3fA9cwnjX46z9\nChRp6HEtkI7JovRIZa1HBbgMQqGiFM4FjxwJatySQpp+MM8yQVJyv9sVCwKBgQCy\ndxHHSCptRz+HV21oAQsRYQNPUh7FWVjSQgWruJtOENpXPtE/2KnKtY+imEskv636\npB7qeZElQ+hwM758A60p+72C9+r3wnY5PkBlxZUJOKIMisS1lx9qHW1K0qY3n0Dv\nzJA+eVRU/y1Do1nSfIUfcDbr6kWouJrI/oe6xdGD9QKBgQDX3JjCz+en+vJf6JYy\nSHwnP4YzAb2jiuDdhsG7YhLBrAM2mjAoPXeQU9Mu/eqjK6JaiBKUAofSWaSVWZJi\nju9pNeQ9cTEBRgIv2t3GyDQCjDMzE7+GIc16TH4wl4ceT6W3enZawUfXi4XnlfTL\no2UJ+Af6Duxn97bQ3nH6vrtjHw==\n-----END PRIVATE KEY-----\n"
client_email = "streamlit-diary-robot@intense-clarity-478212-k2.iam.gserviceaccount.com"
client_id = "110010709702579450772"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-diary-robot%40intense-clarity-478212-k2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# アプリケーションが使用するGoogle Drive/SheetのID
[google_resources]
spreadsheet_id = "1sEzw59aswIlA-8_CTyUrRBLN7OnrRIJERKUZ_bELMrY"
drive_folder_id = "0AHWG1VVKFlpLUk9PVA" # IDの末尾の"?ths=true"は不要です。

# Google Sheetsのシート名
[sheet_names]
registration_sheet = "日記登録用シート"
usable_diary_sheet = "写メ日記集めシート"
account_sheet = "写メ日記アカウント"


